Repository Lithe-Project/Lithe, pull requests merged in 2019-03, with the labels that each got.

#5 Add Donate Option
  src/Miner/MinerManager.cpp
  src/Miner/MinerManager.h
  src/Miner/MiningConfig.cpp
  src/Miner/MiningConfig.h
Labels: Enhancement

#7 Testnet
  src/config/CryptoNoteConfig.h
Labels: Enhancement, Important

#6 add .travis.yml
  .travis.yml
  scripts/build-release.sh
  scripts/checkpointer/delayed-checkpoints.py
  scripts/checkpointer/full-checkpoints.py
  scripts/cross-aarch64.cmake
  scripts/extra/decode
  scripts/extra/encode.py
  scripts/fix_boost_aarch64.sh
  scripts/get_diff_info.sh
  scripts/internal-checkpoints-tool/README.md
  scripts/internal-checkpoints-tool/checkpoints.js
  scripts/internal-checkpoints-tool/package-lock.json
  scripts/internal-checkpoints-tool/package.json
  scripts/makechange.py
  scripts/multi_installer.sh
  scripts/optimize.py
  scripts/setup
Labels: Enhancement

#8 New network for testnet
  scripts/build-release.sh
  scripts/checkpointer/delayed-checkpoints.py
  scripts/checkpointer/full-checkpoints.py
  scripts/extra/encode.py
  scripts/makechange.py
  scripts/multi_installer.sh
  scripts/optimize.py
  scripts/setup
  src/BinaryInfo/daemon.rc
  src/BinaryInfo/service.rc
  src/Errors/Errors.h
  src/WalletApi/Constants.h
  src/WalletService/main.cpp
  src/config/CryptoNoteConfig.h
  src/config/WalletConfig.h
  src/config/version.h.in
  src/crypto/slow-hash.c
  src/zedwallet/Tools.cpp
  src/zedwallet/ZedWallet.cpp
Labels: Important

#12 Mac-OS Fix
  src/Miner/BlockchainMonitor.cpp
  src/WalletBackend/Transfer.cpp
  src/WalletBackend/WalletSynchronizer.cpp
Labels: Bug Fix

#13 Various updates
  src/CryptoNoteCore/CachedBlock.cpp
  src/config/CryptoNoteConfig.h
  src/config/version.h.in
Labels: Bug Fix

#14 Improvements
  .travis.yml
  src/CryptoNoteCore/Checkpoints.cpp
  src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
  src/Miner/Miner.cpp
  src/Utilities/ColouredMsg.h
  src/config/Ascii.h
  src/config/CryptoNoteConfig.h
  src/config/version.h.in
Labels: Enhancement

#15 Add optional unlock height to old zedwallet
  src/CryptoNoteCore/BlockchainCache.cpp
  src/CryptoNoteCore/DatabaseBlockchainCache.cpp
  src/zedwallet/Transfer.cpp
Labels: Enhancement
